name: Matrix strategy

on:
  push:
    branches:
      - main

jobs:
  run-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-22.04]
        mode: [16, 17]
    steps:
      - name: Print exv info
        run: |
          echo "running on os ${{ matrix.os }}"
          echo "Node version: ${{ matrix.node }}"

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Run linux commands
        run: |
          uname -a
          node -v
          echo "hello from matrix job"